### ISSUE TITLE
Support for aarch64

### ISSUE THREAD

**Issue by jsf9k** [geerlingguy/docker-fedora38-ansible#2]
We currently use this Docker image to test our [cisagov](https://github.com/cisagov) Ansible roles.  I am looking to test our Ansible roles on both aarch64 and arm64 platforms, but this image does not support the former.  It would be nice if it did.

**Comment by geerlingguy** [comment]
Thanks! I support arm64 on a few of the other builds, but haven't put that code in here yet. For reference: https://github.com/geerlingguy/docker-ubuntu2204-ansible/blob/master/.github/workflows/build.yml#L56
